In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 2], [4, 1, 0], [1, 3, 1], [5, 0, 0]])

In [3]:
A

array([[1, 2, 2],
       [4, 1, 0],
       [1, 3, 1],
       [5, 0, 0]])

In [8]:
np.hstack((A, A.sum(axis=1)[:, np.newaxis]))

array([[1, 2, 2, 5],
       [4, 1, 0, 5],
       [1, 3, 1, 5],
       [5, 0, 0, 5]])

In [9]:
import pandas as pd

In [76]:
data = pd.read_csv("https://raw.githubusercontent.com/iad34/seminars/master/data_sem1.csv", sep=";")

In [77]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund; Mr. Owen Harris    male   22      1   
1  Cumings; Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen; Miss. Laina  female   26      0   
3       Futrelle; Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen; Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [50]:
data["Surname"] = data["Name"].apply(lambda x: x[:x.find(";")])

In [51]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund; Mr. Owen Harris    male   22      1   
1  Cumings; Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen; Miss. Laina  female   26      0   
3       Futrelle; Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen; Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked    Surname  
0      0         A/5 21171   7.2500   NaN        S     Braund  
1      0          PC 17599  71.2833   C85        C    Cumings  
2      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3      0            113803  53.1000  C123        S   Futrelle  
4      0            373450   8.0500   NaN        S      Allen

In [55]:
data.groupby("Surname").count()

PassengerId  Survived  Pclass  Name  Sex  Age  SibSp  Parch  \
Surname                                                                         
Abbing                      1         1       1     1    1    1      1      1   
Abbott                      2         2       2     2    2    2      2      2   
Abelson                     2         2       2     2    2    2      2      2   
Adahl                       1         1       1     1    1    1      1      1   
Adams                       1         1       1     1    1    1      1      1   
Ahlin                       1         1       1     1    1    1      1      1   
Aks                         1         1       1     1    1    1      1      1   
Albimona                    1         1       1     1    1    1      1      1   
Alexander                   1         1       1     1    1    1      1      1   
Alhomaki                    1         1       1     1    1    1      1      1   
Ali                         2         2       2     2    2    2      2      2   
Allen                       2         2       2     2    2    2      2      2   
Allison                     3         3       3     3    3    3      3      3   
Allum                       1         1       1     1    1    1      1      1   
Andersen-Jensen             1         1       1     1    1    1      1      1   
Anderson                    1         1       1     1    1    1      1      1   
Andersson                   9         9       9     9    9    9      9      9   
Andreasson                  1         1       1     1    1    1      1      1   
Andrew                      1         1       1     1    1    1      1      1   
Andrews                     2         2       2     2    2    2      2      2   
Angle                       1         1       1     1    1    1      1      1   
Appleton                    1         1       1     1    1    1      1      1   
Arnold-Franchi              2         2       2     2    2    2      2      2   
Artagaveytia                1         1       1     1    1    1      1      1   
Asim                        1         1       1     1    1    1      1      1   
Asplund                     4         4       4     4    4    4      4      4   
Astor                       1         1       1     1    1    1      1      1   
Attalah                     2         2       2     2    2    2      2      2   
Aubart                      1         1       1     1    1    1      1      1   
Augustsson                  1         1       1     1    1    1      1      1   
...                       ...       ...     ...   ...  ...  ...    ...    ...   
Wells                       1         1       1     1    1    1      1      1   
West                        3         3       3     3    3    3      3      3   
Wheadon                     1         1       1     1    1    1      1      1   
White                       2         2       2     2    2    2      2      2   
Wick                        2         2       2     2    2    2      2      2   
Widegren                    1         1       1     1    1    1      1      1   
Widener                     1         1       1     1    1    1      1      1   
Wiklund                     1         1       1     1    1    1      1      1   
Wilhelms                    1         1       1     1    1    1      1      1   
Willey                      1         1       1     1    1    0      1      1   
Williams                    4         4       4     4    4    2      4      4   
Williams-Lambert            1         1       1     1    1    0      1      1   
Windelov                    1         1       1     1    1    1      1      1   
Wiseman                     1         1       1     1    1    0      1      1   
Woolner                     1         1       1     1    1    0      1      1   
Wright                      1         1       1     1    1    1      1      1   
Yasbeck                     2         2       2  

In [56]:
data.drop("Name", axis=1)

PassengerId  Survived  Pclass      Sex  Age  SibSp  Parch  \
0              1         0       3     male   22      1      0   
1              2         1       1   female   38      1      0   
2              3         1       3   female   26      0      0   
3              4         1       1   female   35      1      0   
4              5         0       3     male   35      0      0   
5              6         0       3  unknown  NaN      0      0   
6              7         0       1     male   54      0      0   
7              8         0       3     male    2      3      1   
8              9         1       3   female   27      0      2   
9             10         1       2   female   14      1      0   
10            11         1       3   female    4      1      1   
11            12         1       1   female   58      0      0   
12            13         0       3     male   20      0      0   
13            14         0       3  unknown   39      1      5   
14            15         0       3   female   14      0      0   
15            16         1       2   female   55      0      0   
16            17         0       3     male    2      4      1   
17            18         1       2     male  NaN      0      0   
18            19         0       3   female   31      1      0   
19            20         1       3   female  NaN      0      0   
20            21         0       2     male   35      0      0   
21            22         1       2     male   34      0      0   
22            23         1       3   female   15      0      0   
23            24         1       1     male   28      0      0   
24            25         0       3   female    8      3      1   
25            26         1       3   female   38      1      5   
26            27         0       3     male  NaN      0      0   
27            28         0       1     male   19      3      2   
28            29         1       3  unknown  NaN      0      0   
29            30         0       3     male  NaN      0      0   
..           ...       ...     ...      ...  ...    ...    ...   
861          862         0       2     male   21      1      0   
862          863         1       1   female   48      0      0   
863          864         0       3   female  NaN      8      2   
864          865         0       2     male   24      0      0   
865          866         1       2   female   42      0      0   
866          867         1       2   female   27      1      0   
867          868         0       1     male   31      0      0   
868          869         0       3     male  NaN      0      0   
869          870         1       3     male    4      1      1   
870          871         0       3     male   26      0      0   
871          872         1       1   female   47      1      1   
872          873         0       1     male   33      0      0   
873          874         0       3     male   47      0      0   
874          875         1       2   female   28      1      0   
875          876         1       3   female   15      0      0   
876          877         0       3     male   20      0      0   
877          878         0       3     male   19      0      0   
878          879         0       3     male  NaN      0      0   
879          880         1       1   female   56      0      1   
880          881         1       2   female   25      0      1   
881          882         0       3     male   33      0      0   
882          883         0       3   female   22      0      0   
883          884         0       2     male   28      0      0   
884          885         0       3     male   25      0      0   
885          886         0       3   female   39      0      5   
886          887         0       2     male   27      0      0   
887          888         1       1   female   19      0      0   
888          889         0       3   female  NaN      1      2   
889          890         1       1     male  

In [64]:
d = data[data.columns[1:3]].values

In [68]:
d

array([[0, 3],
       [1, 1],
       [1, 3],
       ..., 
       [0, 3],
       [1, 1],
       [0, 3]], dtype=int64)

In [70]:
q = np.array([1, 2])

In [74]:
((d-q[np.newaxis, :])**2).sum(axis=1)

array([2, 1, 1, 1, 2, 2, 2, 2, 1, 0, 1, 1, 2, 2, 2, 0, 2, 0, 2, 1, 1, 0, 1,
       1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 0, 1, 2,
       2, 1, 2, 2, 2, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2, 1, 2, 2, 2, 1, 0, 2, 1,
       2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 2, 0, 1, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 1, 2, 1, 1, 2, 2, 2, 2, 0, 1, 1, 1, 2,
       2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 0,
       1, 2, 1, 1, 2, 2, 0, 1, 1, 0, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2,
       1, 1, 1, 2, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 2, 2, 2, 2, 0, 1, 1, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 0, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 1,
       2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1,
       1, 1,

In [65]:
d.dot(d.T)

array([[ 9,  3,  9, ...,  9,  3,  9],
       [ 3,  2,  4, ...,  3,  2,  3],
       [ 9,  4, 10, ...,  9,  4,  9],
       ..., 
       [ 9,  3,  9, ...,  9,  3,  9],
       [ 3,  2,  4, ...,  3,  2,  3],
       [ 9,  3,  9, ...,  9,  3,  9]], dtype=int64)

In [23]:
data.Sex.value_counts()

male       574
female     312
unknown      5
Name: Sex, dtype: int64

In [28]:
data.loc[1]

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings; Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                           38
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [29]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [30]:
data.Sex.map({"male":1, "female":-1, "unknown":0})

0      1
1     -1
2     -1
3     -1
4      1
5      0
6      1
7      1
8     -1
9     -1
10    -1
11    -1
12     1
13     0
14    -1
15    -1
16     1
17     1
18    -1
19    -1
20     1
21     1
22    -1
23     1
24    -1
25    -1
26     1
27     1
28     0
29     1
      ..
861    1
862   -1
863   -1
864    1
865   -1
866   -1
867    1
868    1
869    1
870    1
871   -1
872    1
873    1
874   -1
875   -1
876    1
877    1
878    1
879   -1
880   -1
881    1
882   -1
883    1
884    1
885   -1
886    1
887   -1
888   -1
889    1
890    1
Name: Sex, dtype: int64

In [44]:
di = dict(zip(data.Name.sort_values(), np.arange(len(data.Name))))

In [40]:
x

845                                Abbing; Mr. Anthony
746                        Abbott; Mr. Rossmore Edward
279                   Abbott; Mrs. Stanton (Rosa Hunt)
308                                Abelson; Mr. Samuel
874              Abelson; Mrs. Samuel (Hannah Wizosky)
365                     Adahl; Mr. Mauritz Nils Martin
401                                    Adams; Mr. John
40      Ahlin; Mrs. Johan (Johanna Persdotter Larsson)
855                         Aks; Mrs. Sam (Leah Rosen)
207                        Albimona; Mr. Nassef Cassem
810                             Alexander; Mr. William
840                        Alhomaki; Mr. Ilmari Rudolf
210                                     Ali; Mr. Ahmed
784                                   Ali; Mr. William
730                      Allen; Miss. Elisabeth Walton
4                             Allen; Mr. William Henry
305                     Allison; Master. Hudson Trevor
297                       Allison; Miss. Helen Loraine
498    All