### Задачи на numpy

In [1]:
import numpy as np

Создаем матрицу голосования

In [2]:
x=np.array([[12,9,2],[3,17,2],[21,0,0],[9,4,8]])

Проверяем число студентов в аудитории

In [4]:
np.sum(x, axis=1)

array([23, 22, 21, 21])

Каких ответов больше: да или нет?

In [5]:
np.sum(x, axis=0)

array([45, 30, 12])

In [6]:
x.sum(axis=0)

array([45, 30, 12])

In [7]:
x.sum()

87

То же самое через матричное произведение

In [10]:
y=np.ones((3,1))

In [8]:
x.shape

(4, 3)

In [12]:
np.dot(x, y)

array([[ 23.],
       [ 22.],
       [ 21.],
       [ 21.]])

In [16]:
x.dot(y).ravel()

array([ 23.,  22.,  21.,  21.])

In [14]:
x@y  # в python3

array([[ 23.],
       [ 22.],
       [ 21.],
       [ 21.]])

In [18]:
z=np.ones((1,4))
z@x

array([[ 45.,  30.,  12.]])

Вытянуть матрицу в вектор:

In [19]:
x.ravel()

array([12,  9,  2,  3, 17,  2, 21,  0,  0,  9,  4,  8])

Считаем разницу между проголосовавшими "да" и "нет"

In [20]:
x@np.array([1,-1,0])

array([  3, -14,  21,   5])

Составляем бинарный столбец: больше ли ответов "да", чем "нет", на этот вопрос? (True - да, False - нет)

In [24]:
x[:,0] > x[:,1]

array([ True, False,  True,  True], dtype=bool)

Добавляем новые данные:

In [25]:
w = np.array(((0, 11, 12),(21,0,0)))

In [26]:
print(w)

[[ 0 11 12]
 [21  0  0]]


In [34]:
u=np.vstack([x, w])

Добавляем столбец, в котором 1 показывает, что вопрос был раньше, 0 - что ответ новый

In [28]:
q=np.ones((4,1))

In [29]:
e=np.zeros((2,1))

In [30]:
t=np.vstack([q,e])   # первый вариант задать матрицу для добавления

In [46]:
t = np.array([1, 1, 1, 1, 0, 0])   

In [48]:
t.shape

(6,)

In [49]:
t[:, np.newaxis]   # второй вариант создать матрицу для добавления к исходной матрице справа

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0]])

In [51]:
t[:, np.newaxis].shape

(6, 1)

In [69]:
matrix = np.hstack([u,t[:, np.newaxis]])  # добавляем матрицу справа

In [38]:
u.shape, t.shape

((6, 3), (6,))

Деление матрицы на сумму по строкам

In [56]:
x_sum = x.sum(axis=1)

In [58]:
x_sum.shape

(4,)

In [61]:
x_sum[:, np.newaxis]

array([[23],
       [22],
       [21],
       [21]])

In [63]:
x / x_sum[:, np.newaxis]

array([[ 0.52173913,  0.39130435,  0.08695652],
       [ 0.13636364,  0.77272727,  0.09090909],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.42857143,  0.19047619,  0.38095238]])

In [64]:
x.shape, x_sum[:, np.newaxis].shape

((4, 3), (4, 1))

Подробнее про np.newaxis - google numpy broadcasting / numpy newaxis

Индексация

In [67]:
x[[2,1]]

array([[21,  0,  0],
       [ 3, 17,  2]])

Перемешать строки матрицы

In [68]:
np.random.permutation(x)

array([[21,  0,  0],
       [ 3, 17,  2],
       [ 9,  4,  8],
       [12,  9,  2]])

In [70]:
np.random.permutation(matrix)

array([[21,  0,  0,  0],
       [ 9,  4,  8,  1],
       [21,  0,  0,  1],
       [12,  9,  2,  1],
       [ 3, 17,  2,  1],
       [ 0, 11, 12,  0]])

Альтернативный вариант: задаем индексацию для перемешивания

In [71]:
index = np.random.permutation(np.arange(6))

In [72]:
print(index)

[3 1 5 0 4 2]


In [73]:
index

array([3, 1, 5, 0, 4, 2])

In [76]:
result = matrix[index]

In [77]:
matrix

array([[12,  9,  2,  1],
       [ 3, 17,  2,  1],
       [21,  0,  0,  1],
       [ 9,  4,  8,  1],
       [ 0, 11, 12,  0],
       [21,  0,  0,  0]])

Создаем датафрейм с данными

In [78]:
import pandas as pd

In [81]:
df = pd.DataFrame(data=result, index=["Q1","Q2","Q3","Q4","Q5","Q6"], columns=["Yes","No","Ignore","Label"])

In [82]:
df

Yes  No  Ignore  Label
Q1    9   4       8      1
Q2    3  17       2      1
Q3   21   0       0      0
Q4   12   9       2      1
Q5    0  11      12      0
Q6   21   0       0      1

Загрузка данных из csv

In [85]:
data = pd.read_csv("https://raw.githubusercontent.com/iad34/seminars/master/data_sem1.csv", sep=";")

In [87]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund; Mr. Owen Harris    male  22.0      1   
1  Cumings; Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen; Miss. Laina  female  26.0      0   
3       Futrelle; Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen; Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

Взять строку датафрейма:

In [94]:
data.loc[4]

PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen; Mr. William Henry
Sex                                male
Age                                  35
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 4, dtype: object